alleeResume/Controllers/resumeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace alleeResume.Controllers
{
    public class resumeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Education()
        {
            ViewBag.Message = "education page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }

        public ActionResult workHistory()
        {
            ViewBag.Message = "work history page.";

            return View();
        }

        public ActionResult skills()
        {
            ViewBag.Message = "skills page.";

            return View();
        }

        public ActionResult references()
        {
            ViewBag.Message = "references page.";

            return View();
        }

        public ActionResult projects()
        {
            ViewBag.Message = "projects page.";

            return View();
        }
    }
}

alleeResume/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="~/Content/Site.css">
    <title>@ViewBag.Title - Nick Allee Resume</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Nicholas Christopher Allee", "Index", "resume", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Education", "Education", "resume")</li>
                    <li>@Html.ActionLink("Work History", "workHistory", "resume")</li>
                    <li>@Html.ActionLink("Contact", "Contact", "resume")</li>
                    <li>@Html.ActionLink("Skills", "skills", "resume")</li>
                    <li>@Html.ActionLink("References", "references", "resume")</li>
                    <li>@Html.ActionLink("Projects", "projects", "resume")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Resume Webpage</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>

alleeResume/Views/resume/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}

<body>
    <ul class="lglist">
        <li class="lglist-item">
            <div class="mock-box"></div>
            <a class="lglist-item-content">
                <h2>
                    Maryville, Mo 64468
                    <br/>
                    816-787-4041
                </h2>
                <h3>
                    <strong>Email:</strong>   <a href="mailto:nickallee8529@gmail.com">nickallee8529@gmail.com</a>
                </h3>
            </a>
        </li>
    </ul>
</body>

alleeResume/Views/resume/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>Nick Allee</h1>
    <img src="~/files/nickPhoto.png" />
    <p class="lead">A 4th Year Computer Science and Cyber-Security Major with an aptitude for learning new things. I am an avid programmer with an interest in data science and finance. I have great work experience from the food service industry to teaching computer classes. I Graduate May 9 and am ready to find my first fulltime job in the Computer Science Industry. </p>
    <p><a href="~/files/nickalleeresume2_15_2020.docx" class="btn btn-primary btn-lg">Download my resume here &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>something here</h2>
        <p>
            what to put here
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
</div>

alleeResume/Views/resume/education.cshtml
@{
    ViewBag.Title = "Education";
}
<body>
    <ul class="lglist">
        <li class="lglist-item">
            <div class="mock-box"><img src="~/files/spoofhound.png" width="100" style="object-fit:cover," /></div>
            <a href="http://www.mhs.maryville.k12.mo.us/" class="lglist-item-content">
                <h2> Highschool</h2>
                <p>box here with my highschool information</p>
            </a>
        </li>
        <li class="lglist-item">
            <div class="mock-box"><img src="~/files/bearcat.png" width="100" style="object-fit:cover,"/></div>
            <a href="https://www.nwmissouri.edu/" class="lglist-item-content">
                <h2>College</h2>
                <p>box here with my college information</p>
            </a>
        </li>
    </ul>
</body>
can you see this? 
yes
dope i'm trying to connect to your server so I can see the app

alleeResume/Views/resume/projects.cshtml
@{
    ViewBag.Title = "Projects";
}
    <body>
        <ul class="lglist">
            <li class="lglist-item">
                <div class="mock-box"></div>
                <a class="lglist-item-content">
                    <h2> Featured Projects</h2>
                    <p>box here with 3 projects in it split horizantally</p>
                </a>
            </li>
            <li class="lglist-item">
                <div class="mock-box"><img src="~/files/pythonLogo.png" width="100" /></div>
                <a class="lglist-item-content">
                    <h2>Python Projects</h2>
                    <p>box here with a link to the python projects page</p>
                </a>
            </li>
            <li class="lglist-item">
                <div class="mock-box"><img src="~/files/cSharp.png" width="100" /></div>
                <a class="lglist-item-content">
                    <h2>C# Projects</h2>
                    <p>box here with a link to the C# projects page</p>
                </a>
            </li>
            <li class="lglist-item">
                <div class="mock-box"><img src="~/files/presentation.png" width="100" /></div>
                <a class="lglist-item-content">
                    <h2>papers and presentations</h2>
                    <p>box here with a link to the papersPresentations page</p>
                </a>
            </li>
            <li class="lglist-item">
                <div class="mock-box"><img src="~/files/github.jpg" width="100" /></div>
                <a class="lglist-item-content">
                    <h2>all Github Projects</h2>
                    <p>box here with a link to the github portfolio page and photo of github</p>
                </a>
            </li>
        </ul>
    </body>

alleeResume/Views/resume/references.cshtml
@{
    ViewBag.Title = "References";
}
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <ul class="lglist">
            <li class="lglist-item">
                <div class="mock-box"></div>
                <a href="https://www.nwmissouri.edu/csis/directory/hoot.htm" class="lglist-item-content">
                    <h2> Machine Learning Supervisor</h2>
                    <p>box here with dr.hoots information</p>
                </a>
            </li>

            <li class="lglist-item">
                <div class="mock-box"></div>
                <a href="https://www.nwmissouri.edu/csis/directory/eloe.htm" class="lglist-item-content">
                    <h2>Data Structures Supervisor</h2>
                    <p>box here with dr eloes information</p>
                </a>
            </li>


            <li class="lglist-item">
                <div class="mock-box"></div>
                <a href="http://www.nts.maryville.k12.mo.us/directory.html" class="lglist-item-content">
                    <h2>Northwest Technical School Supervisor</h2>
                    <p>box here with lori tallys information</p>
                </a>
            </li>
        </ul>
    </body>

alleeResume/Views/resume/skills.cshtml
@{
    ViewBag.Title = "Skills and Activities";
}
    <p>
        •	Python, C, Java, Bash, Solidity, Linux command line,
        C#, OSForensics, WinHex, Git source control, and
        Wireshark
        •	TestOut Ethical Hacking Certification (In Progress)
        •	TestOut PC Pro Certification (Completed May 2016)
        •	Cyber Defense Club
        •	National Honor Society for the
        Computing Disciplines
        •	Association of Computing Machinery
    </p>

alleeResume/Views/resume/workHistory.cshtml
@{
    ViewBag.Title = "Work History";
}

<div class="jumbotron">
    <h1>Work History</h1>
</div>
<hr width="100%" size=1>
<div>
    <h2>Teaching Assistant</h2>
    <ul>
        <li>Computer Science Department Northwest Missouri State University Maryville MO</li>
        <li>January 2017 – Present</li>
        <li>Programming 1, Scientific Computing, Data Structures, and Machine Learning (Graduate Level)</li>
        <li>Grade papers, quizzes, and tests</li>
        <li>Assist students with coursework</li>
        <li>Conduct study sessions to increase core competencies</li>
        <li>Assist the instructor with his lectures by coding on the overhead screen and managing PowerPoints</li>
        <li>Create programming projects</li>
    </ul>
</div>
<hr width="100%" size=1>
<div>
    <h2>Technical School Computer Teacher</h2>
    <ul>
        <li>Northwest Technical School Maryville, MO</li>
        <li>January 2019 - Present</li>
        <li>Conduct instructional classes regarding basic technology skills</li>
        <li>Educate students in fundamentals of using windows, browsers, and basic settings</li>
        <li>Improve competencies in basic computer security and best secure practices for browsing the web</li>
    </ul>
</div>
<hr width="100%" size=1>
<div>
    <h2>Factory Machine Operator</h2>
    <ul>
        <li>Kawasaki Motors Maryville, MO</li>
        <li>May 2019 - July 2019</li>
        <li>Operate heavy machinery to develop cylinder heads for lawn mower engines</li>
    </ul>
</div>
<hr width="100%" size=1>
<div>
    <h2>Fully Trained Pizza Worker</h2>
    <ul>
        <li>Pagliai’s Pizza	 Maryville, MO</li>
        <li>February 2014 - February 2019</li>
        <li>Craft custom food and manage point of sale transactions</li>
        <li>Manage six to eight employees cleaning and closing of the restaurant</li>
        <li>Train new employees on proper working techniques</li>
        <li>Ensure delivery of food to customers both inside and out of town with company car</li>
    </ul>
</div>